name: CI
on:
  - push
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node:
          - 18.x
        os:
          - ubuntu-latest
          - macOS-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Installation
        run: yarn install
      - name: Create temp folder
        run: mkdir temp
      - name: Run zest unit tests
        run: |
          if [ -d "folder-name" ]; then
            node --loader ts-node/esm .baldrick-zest.ts
          else
            echo "No zest files. Skipping"
          fi
      - name: Run pest integration tests
        run: |
          for file in $(find pest-spec -name '*.pest.yaml'); do
            npx baldrick-pest@latest test --spec-file $file
          done
      - name: Build
        run: yarn build
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Pest
          path: report/*.pest.mocha.json
          reporter: mocha-json
